version: '3.5'

services:
  database:
    image: postgres
    container_name: postgres_shard1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres:/data/postgres
    restart: unless-stopped
  redis:
    container_name: redis
    image: 'bitnami/redis:6.2'
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - ${REDIS_DATA}:/bitnami/redis/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
  api:
    build: ./services/api
    container_name: shortner-api
    command: sh -c "dockerize -wait tcp://database:5432 -wait tcp://redis:6379 npm start"
    depends_on:
      - database
    environment:
      API_PORT: ${API_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
    ports:
      - ${API_PORT}:${API_PORT}

networks:
  postgres:
    driver: bridge
